#!/bin/bash
# Copyright (C) 2022 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

TEST_PARAMS=(${1//-/ })

TEST_NAME=$(basename ${TEST_PARAMS[0]})
TEST_PATH=$(dirname ${TEST_PARAMS[0]})
TOKEN_DRIVER=${TEST_PARAMS[1]}

if [ -f "./tmp.${TOKEN_DRIVER}/testvars" ];  then
    source ./tmp.${TOKEN_DRIVER}/testvars
else
    exit 77 # token not configured, skip
fi

if [ -f "${TEST_PATH}/t${TEST_NAME}" ]; then
    COMMAND="${TEST_PATH}/t${TEST_NAME}"
else
    COMMAND="./t${TEST_NAME}"
fi

echo "executing ${COMMAND}"
${COMMAND}
