#!/bin/bash
# Copyright (C) IBM Corp. 2022
# SPDX-License-Identifier: Apache-2.0

test -z "${TESTSDIR}" && exit 77
source "${TESTSDIR}/helpers.sh" || exit 1
echo "set breakpoint pending on" > "${TMPPDIR}/ossl.gdb"

echo "##################################################"
echo "## Tests with openssl commands"
echo "##"
echo "## version:"
echo "## $(openssl version)"
echo "##"

echo "##################################################"
echo "## EC: sign/verify (pkcs11/file)"
echo "##"

ossl '
dgst -sign "${URI_KEY_ECDSA_PRV}"
     -sha256
     -out "${TMPPDIR}/random-1k.bin.ec-sig"
     "${TMPPDIR}/random-1k.bin"' \
|| exit 99

ossl '
dgst -verify "${FILE_PEM_ECDSA_PUB}"
     -sha256
     -signature "${TMPPDIR}/random-1k.bin.ec-sig"
     "${TMPPDIR}/random-1k.bin"' \
|| exit 99

echo "##################################################"
echo "## EC: tls-server/client (ECDHE-ECDSA-AES256-GCM-SHA384)"
echo "##"

ossl '
s_server -brief -CAfile ${FILE_PEM_CA_CRT}
         -key ${URI_KEY_ECDSA_PRV}
         -cert ${FILE_PEM_ECDSA_CRT}
         -cipher ECDHE-ECDSA-AES256-GCM-SHA384
         -www -accept localhost:4433 -naccept +1' \
2> "${TMPPDIR}/server.log" &

# wait for server start
sleep 1

echo "Q" | \
ossl '
s_client -brief -CAfile ${FILE_PEM_CA_CRT}
         -connect localhost:4433
         -tls1_2' \
2> "${TMPPDIR}/client.log"

if [ $? -ne 0 ]; then
  echo "client failed"
  echo "log start -------------"
  cat "${TMPPDIR}/client.log"
  echo "log end ---------------"
  exit 99
fi
echo "client: ok"

# get server status
wait $!
if [ $? -ne 0 ]; then
  echo "server failed"
  echo "log start -------------"
  cat "${TMPPDIR}/server.log"
  echo "log end ---------------"
  exit 99
fi
echo server: ok

echo "##################################################"
echo "## RSA: encrypt/decrypt (file/pkcs11)"
echo "##"

echo "## encrypt data"
ossl '
pkeyutl -encrypt -pkeyopt rsa_padding_mode:none
        -pubin -inkey "${FILE_PEM_RSA4K_PUB}"
        -in  "${TMPPDIR}/random-512.bin"
        -out "${TMPPDIR}/data.enc"' \
|| exit 99

echo "## decrypt data"
ossl '
pkeyutl -decrypt -pkeyopt rsa_padding_mode:none
        -inkey "${URI_KEY_RSA4K_PRV}"
        -in  "${TMPPDIR}/data.enc"
        -out "${TMPPDIR}/data.dec"' \
|| exit 99

echo "## compare clear-text results"
diff -q "${TMPPDIR}/random-512.bin" "${TMPPDIR}/data.dec" \
|| exit 99
echo "diff: identical results"
rm -f "${TMPPDIR}/data.enc" "${TMPPDIR}/data.dec"

echo "##################################################"
echo "## RSA: sign/verify (pkcs11/file)"
echo "##"

ossl '
dgst -sign "${URI_KEY_RSA4K_PRV}"
     -sha256
     -out "${TMPPDIR}/random-1k.bin.rsa-sig"
     "${TMPPDIR}/random-1k.bin"' \
|| exit 99

ossl '
dgst -verify "${FILE_PEM_RSA4K_PUB}"
     -sha256
     -signature "${TMPPDIR}/random-1k.bin.rsa-sig"
     "${TMPPDIR}/random-1k.bin"' \
|| exit 99

exit 0
