set breakpoint pending on
break ps_prov_init
break ps_prov_teardown
break ps_prov_gettable_params
break ps_prov_get_params
break ps_prov_query_operation
break ps_prov_get_reason_strings
break ps_prov_get_capabilities
disable
